# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 08:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polluser',
            name='last_seen',
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 15, 8, 41, 57, 447290, tzinfo=utc), verbose_name='date published'),
        ),
    ]
